/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.4.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as _types from "../_types.js";
import type * as activities from "../activities.js";
import type * as auth from "../auth.js";
import type * as channels_controller from "../channels/controller.js";
import type * as documents from "../documents.js";
import type * as folders_controller from "../folders/controller.js";
import type * as helper from "../helper.js";
import type * as http from "../http.js";
import type * as lists_controller from "../lists/controller.js";
import type * as members from "../members.js";
import type * as messages_controller from "../messages/controller.js";
import type * as organizations from "../organizations.js";
import type * as presence from "../presence.js";
import type * as profile from "../profile.js";
import type * as requests from "../requests.js";
import type * as spaces_controller from "../spaces/controller.js";
import type * as tasks from "../tasks.js";
import type * as userData_controller from "../userData/controller.js";
import type * as users_controller from "../users/controller.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  _types: typeof _types;
  activities: typeof activities;
  auth: typeof auth;
  "channels/controller": typeof channels_controller;
  documents: typeof documents;
  "folders/controller": typeof folders_controller;
  helper: typeof helper;
  http: typeof http;
  "lists/controller": typeof lists_controller;
  members: typeof members;
  "messages/controller": typeof messages_controller;
  organizations: typeof organizations;
  presence: typeof presence;
  profile: typeof profile;
  requests: typeof requests;
  "spaces/controller": typeof spaces_controller;
  tasks: typeof tasks;
  "userData/controller": typeof userData_controller;
  "users/controller": typeof users_controller;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
