name: Playwright Tests for Vite React App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      # Start the Vite server in the background
      - name: Start Vite server
        run: npm run dev -- --port 3000 &
        env:
          NODE_ENV: test

      # Wait for Vite server to be ready
      - name: Wait for Vite server to start
        run: npx wait-on http://localhost:3000

      # Install Playwright browsers and dependencies
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright Tests
        run: npx playwright test

      # Optionally, collect test artifacts (e.g., screenshots, videos)
      - name: Upload Playwright Artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-artifacts
          path: |
            test-results/
            screenshots/
            videos/
